id: IF1F163BB
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:12:22.046437+00:00
last_modified: 2022-12-14 18:12:22.046442+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-066-007
  title: Toh_249-The_Sutra_Teaching_the_Four_Factors-v2
bases:
  565B:
    source_metadata: null
    order: 1
    base_file: 565B.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
